name: Test Git LFS with GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Verify LFS files
        run: |
          echo "Checking LFS file status..."
          file assets/images/branding/rey-it-solutions-logo-003/rey-it-solutions-logo-003.jpg
          ls -lah assets/images/branding/rey-it-solutions-logo-003/rey-it-solutions-logo-003.jpg

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Check built files
        run: |
          echo "Checking built files..."
          if [ -f "_site/assets/images/branding/rey-it-solutions-logo-003/rey-it-solutions-logo-003.jpg" ]; then
            file _site/assets/images/branding/rey-it-solutions-logo-003/rey-it-solutions-logo-003.jpg
            ls -lah _site/assets/images/branding/rey-it-solutions-logo-003/rey-it-solutions-logo-003.jpg
          else
            echo "File not found in _site!"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
